import { SiteHeader } from "@/components/site-header";
import "../styles/globals.css";
import { Providers } from "./providers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html suppressHydrationWarning>
      <body className="min-h-screen bg-white font-sans text-slate-900 antialiased dark:bg-slate-900 dark:text-slate-50">
        <Providers>
          <div className="flex min-h-screen flex-col">
            <SiteHeader />
            <div className="container flex-1">{children}</div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
